### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by lubislutfi** [cloudlang/IDEA-agent#3]
![image](https://user-images.githubusercontent.com/33612504/101629251-062dd000-3a5c-11eb-82e1-1a5449f8f627.png)

![image](https://user-images.githubusercontent.com/33612504/101629175-e696a780-3a5b-11eb-8d80-7c4ae17ac156.png)

I've restart IDE after insert '-javaagent:XXXXX'
but still not working,
regards.

**Comment by HLBTyhs** [comment]
me too

**Comment by niinortey** [comment]
Same problem.

**Comment by cloudlang** [comment]
ide-eval-resetter-2.1.6_2.zip is recommended.
